version: "3.9"

services:
  db:
    image: mysql:8
    container_name: leave_mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: leave_api
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  mysql_data: